name: Daily Script at 1:17 PM

on:
  schedule:
    - cron: '17 13 * * *'  # 1:10 PM UTC daily
  workflow_dispatch:

jobs:
  run-daily-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Checkout the code from the repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run your script
        run: python your_script.py  # Run the Python script

      - name: Show output in logs
        run: cat output.txt  # Display the output in the logs

      - name: Upload output.txt as artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-file
          path: output.txt  # Upload the output file as an artifact
